export const Projects = [
  {
    id: 1,
    color: "from-green-300 to-purple-300",
    title: "ZippyPlan",
    desc: "A web app for managing meetings, contacts, and communication with real-time sync and video conferencing. Designed for collaboration, scalability, and efficiency in scheduling.",
    img: "/zippyplanImage.png",
    link: "https://zippyplan.com",
    technologies: ["/reactIcon.png", "/apiIcon.png", "/tailwind.png"],
  },
  {
    id: 2,
    color: "from-purple-300 to-red-300",
    title: "Noteify",
    desc: "A desktop application developed using Electron, designed for easy note management. It allows users to create, update, delete, and read notes in a simple and user-friendly interface.",
    img: "/noteifyAppImage.png",
    link: "https://chetreenelson.github.io/todoApp/",
    technologies: ["/html5.png", "/cssIcon2.png", "/javascript.png"],
  },
  {
    id: 3,
    // color: "from-red-300 to-blue-300",
    title: "Recipe App",
    desc: "This app lets you explore a wide range of food recipes with a user-friendly and attractive design. You can browse, search, and find detailed instructions and ingredient lists for each recipe, making cooking easy and fun.",
    img: "/recipeAppImage.png",
    link: "https://recipe-app-version1.vercel.app/",
    technologies: ["/reactIcon.png", "/apiIcon.png", "/tailwind.png"],
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "Text-Utlis App",
    desc: "Developed a Text Utils app that offers text case changing, word and character counts, text-to-speech, customizable modes, and additional features for enhanced functionality.",
    img: "/textUtilsAppImage.png",
    link: "https://textutils7.netlify.app/",
    technologies: ["/reactIcon.png", "/bootstrap.png"],
  },
];
